# Generated by Django 4.0.4 on 2022-10-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
